@startuml usecase
left to right direction
ユーザー --> (メールアドレス、Googleアカウントなどでログインできる)
ユーザー --> (記事の作成、保存、編集、削除ができる)
ユーザー --> (記事を任意のフォルダごとに分けられる)
ユーザー --> (記事にタグをつけることができる)
ユーザー --> (記事を日付やタグで検索できる)
ユーザー --> (記事に画像やWebページを取り込むことができる)
ユーザー --> (ログアウトできる)
@enduml