version: '3.8'
services:
  frontend:
    container_name: front
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    tty: true
    stdin_open: true
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app:cached
      - /app/node_modules
    tty: true
    stdin_open: true
