version: '3.8'
services:
  frontend:
    container_name: front
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    tty: true
    stdin_open: true
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app:cached
      - /app/node_modules
    tty: true
    stdin_open: true
  mysql:
    container_name: database
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql